
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package malemela.mv;

import java.awt.*;
import java.io.*;
import java.text.DecimalFormat;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author MAROPENG VANESSA MALEMELA
 */
public class MalemelaMVForm extends javax.swing.JFrame {
    
    public MalemelaMVForm() {
        initComponents();
        pCustomer.setVisible(false);
        btnPrint.setVisible(false);
        setSize(pLogin.getWidth(),pLogin.getHeight()+70);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLogin = new javax.swing.JPanel();
        lbCashier = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        jTFCashier = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        pCustomer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfOrderNo = new javax.swing.JTextField();
        cbFlavour = new javax.swing.JComboBox();
        cbShape = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cbxYes = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDisplay = new javax.swing.JTextArea();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ruby's Delights");
        setBackground(new java.awt.Color(204, 159, 144));
        setForeground(new java.awt.Color(204, 159, 144));
        setLocation(new java.awt.Point(250, 185));

        pLogin.setBackground(new java.awt.Color(204, 204, 204));
        pLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lbCashier.setText("Enter Cashier Name:");

        lbPassword.setText("Enter Login Password:");

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\MAROPENG\\Documents\\2024 School\\Ruby Notes\\OOR216D\\Assignments\\TestMV\\Ok.jpg")); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pLoginLayout = new javax.swing.GroupLayout(pLogin);
        pLogin.setLayout(pLoginLayout);
        pLoginLayout.setHorizontalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCashier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFCashier, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );
        pLoginLayout.setVerticalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCashier)
                    .addComponent(lbPassword)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCashier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        pCustomer.setBackground(new java.awt.Color(204, 204, 255));
        pCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 255))); // NOI18N
        pCustomer.setForeground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setText("!!!Customer Order Details!!!");

        jLabel2.setText("Enter Order Number:");

        jLabel3.setText("Select A Cake Flavour:");

        jLabel4.setText("Select Cake Shape:");

        cbFlavour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CHOCOLATE", "VANILLA", "RED VELVET", "FRUIT" }));

        cbShape.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SQUARE", "ROUND" }));

        jLabel5.setText("Late Order:");

        cbxYes.setText("Yes");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/malemela/mv/Ok.jpg"))); // NOI18N
        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/malemela/mv/Retry1.jpg"))); // NOI18N
        jButton2.setText("Next Day");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        taDisplay.setColumns(20);
        taDisplay.setRows(5);
        jScrollPane2.setViewportView(taDisplay);

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/malemela/mv/Print.png"))); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCustomerLayout = new javax.swing.GroupLayout(pCustomer);
        pCustomer.setLayout(pCustomerLayout);
        pCustomerLayout.setHorizontalGroup(
            pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCustomerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCustomerLayout.createSequentialGroup()
                        .addGap(0, 138, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(pCustomerLayout.createSequentialGroup()
                        .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pCustomerLayout.createSequentialGroup()
                                .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfOrderNo)
                                    .addComponent(cbFlavour, 0, 117, Short.MAX_VALUE)))
                            .addGroup(pCustomerLayout.createSequentialGroup()
                                .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxYes)
                                    .addComponent(cbShape, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pCustomerLayout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jButton1)))
                        .addGap(18, 18, 18)
                        .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(pCustomerLayout.createSequentialGroup()
                                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))
                        .addContainerGap())))
        );

        pCustomerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5});

        pCustomerLayout.setVerticalGroup(
            pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pCustomerLayout.createSequentialGroup()
                        .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbFlavour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbShape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(cbxYes)))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnPrint)
                    .addComponent(jButton2))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
      File pass=new File("Password.txt");
      boolean status=false;
      
      try{
            BufferedReader br = new BufferedReader(new FileReader(pass));
            String line="";
            line=br.readLine(); 
             br.close();
         try {
               
               char[] passChar=passwordField.getPassword();
               String passCode=new String(passChar);
              if(jTFCashier.getText().equals("")==false)
              {
                 while(line !=null)
                 {
                   if(passCode.equals(line))
                   {
                     pLogin.setVisible(false);
                       setSize(600, 375);
                     pCustomer.setVisible(true);
                     status=true;
                     break;
                    
                   }else
                   {
                     passwordField.setText("");
                     line=br.readLine();
                   }
                 }
              }else
                 JOptionPane.showMessageDialog(null, "Cashier Name not Entered"); 
            } catch (Exception e) {
              JOptionPane.showMessageDialog(null, "Incorrect Password Entered");
            }
       } catch (IOException e) {
            
            JOptionPane.showMessageDialog(null, "File not accessible");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        DecimalFormat fm=new DecimalFormat("R0.00");
        
        String flavour=(String) cbFlavour.getSelectedItem();
        String shape=(String) cbShape.getSelectedItem();
        String orderNum=tfOrderNo.getText();
        boolean checked=cbxYes.isSelected();
        char lateOrder=' ';
         
        if(checked==true)
        {
          lateOrder='Y';
        }
 
        MalemelaMV obj=new MalemelaMV(flavour, shape, lateOrder, orderNum); 
        
        double paid=0.0;
        double change=0.0;
        
        if(orderNum != "" )
        {
            boolean valid=obj.checkOrderNo(orderNum);
            if(valid==true)
            {
                JOptionPane.showMessageDialog(null,"Amount Due:"+fm.format(obj.calculateTotal()));
                paid=Double.parseDouble(JOptionPane.showInputDialog("Enter amount paid:"));
                change=obj.determineChange(paid);
                taDisplay.setText(obj.displayOrder(paid));
                btnPrint.setVisible(true);
                
            }else
              JOptionPane.showMessageDialog(null, "Wrong Order Number Format!Hint:RD23*****!!");  
           
        }else
            JOptionPane.showMessageDialog(null, "Order Number Missing!!!");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
       File input=new File("CakeOrders.txt");
       String line="";
       
        try {
               BufferedWriter bw=new BufferedWriter(new FileWriter(input, true));
               
               line=line+tfOrderNo.getText()+"-"+(String)cbFlavour.getSelectedItem()+"-"+(String)cbShape.getSelectedItem();
               line="\n"+line;
               bw.write(line);
               
               bw.close();   
        } catch (IOException e) {
             JOptionPane.showMessageDialog(null, "Writing to file failed");
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String flavour=(String) cbFlavour.getSelectedItem();
        String shape=(String) cbShape.getSelectedItem();
        String orderNum=tfOrderNo.getText();
        boolean checked=cbxYes.isSelected();
        char lateOrder=' ';
         
        if(checked==true)
        {
          lateOrder='Y';
        }
 
        MalemelaMV obj=new MalemelaMV(flavour, shape, lateOrder, orderNum); 
        
        
        pCustomer.setVisible(false);
        taDisplay.setText("");
        tfOrderNo.setText("");
        jTFCashier.setText("");
        passwordField.setText("");
        pLogin.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MalemelaMVForm().setVisible(true);
            }
        });
     
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox cbFlavour;
    private javax.swing.JComboBox cbShape;
    private javax.swing.JCheckBox cbxYes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFCashier;
    private javax.swing.JLabel lbCashier;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JPanel pCustomer;
    private javax.swing.JPanel pLogin;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextArea taDisplay;
    private javax.swing.JTextField tfOrderNo;
    // End of variables declaration//GEN-END:variables
  
}
