name: Build and deploy JAR app to Azure Web App - SavvyBuy-223019412

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install  # You may want to specify the pom.xml if it's not in the root

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'  # Adjust the path if necessary

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_98C504C2E0374BF19A0D6C649A07F82E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DEC584A317EA45F7B3335E95AF4D5DCD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AF6081ABCCE54DB9B7F36F0A876A7B37 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SavvyBuy-223019412'  # Ensure this is your actual Azure app name
          slot-name: 'Production'  # Adjust if you're using a different slot (e.g., staging)
          package: '${{ github.workspace }}/target/*.jar'  # Ensure this path matches the artifact downloaded

